### PR TITLE
Update v5.0.0

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
Hi @asford 
This fixes the feedstock, and upgrades to version 5.0.0 - re rendered with grayskull, fixed dependencies.
Could you please take a look and merge.
Thanks and Regards.

**Comment by gabrielcnr** [comment]
@marcelotrevisani can you please take a look if this is good to go as it seems to be? thank you!!

**Comment by marcelotrevisani** [comment]
@conda-forge-admin please rerender

**Comment by marcelotrevisani** [comment]
As this PR was created on October and the maintainers of this feedstock didn’t review it. I’m reviewing and merging it as a core member of conda-forge. Thanks @rxm7706 for your contribution

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please restart ci

**Comment by marcelotrevisani** [comment]
``quay`` seems to be unstable. Unfortunately, I am going to wait for it to be stable again so I can rerun the pipeline and after that if everything is fine I can merge it

**Comment by marcelotrevisani** [comment]
It might be related to 
https://status.quay.io/incidents/z7sbjqmb34p1

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please restart ci

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
